export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_LOGS_SUCCESS  = 'LOAD_LOGS_SUCCESS';
export const CREATE_LOG_SUCCESS = 'CREATE_LOG_SUCCESS';
export const UPDATE_LOG_SUCCESS = 'UPDATE_LOG_SUCCESS';
export const DELETE_LOG_SUCCESS = 'DELETE_LOG_SUCCESS';

export const LOAD_ACHIEVEMENTS_SUCCESS  = 'LOAD_ACHIEVEMENTS_SUCCESS';
export const CREATE_ACHIEVEMENT_SUCCESS = 'CREATE_ACHIEVEMENT_SUCCESS';
export const UPDATE_ACHIEVEMENT_SUCCESS = 'UPDATE_ACHIEVEMENT_SUCCESS';
export const DELETE_ACHIEVEMENT_SUCCESS = 'DELETE_ACHIEVEMENT_SUCCESS';

export const LOAD_PAGES_SUCCESS  = 'LOAD_PAGES_SUCCESS';
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS';
export const UPDATE_PAGE_SUCCESS = 'UPDATE_PAGE_SUCCESS';
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS';

export const TOGGLE_LOG_IN = 'TOGGLE_LOG_IN';
